cc_library( name = 'leet_code_solution',
          srcs = [
                  'reverse_string.cc',
                  ],
          deps = [
                  '//base:base',
                 ],
         )

cc_test(name = 'leet_solution_test',
          srcs = [
                  'leet_solution_test.cc',
                 ],
          deps = [
                  ":leet_code_solution",
                 ],
          )
