# Copyright 2014. All Rights Reserved.
# Author: rentongzh@gmail.com (Rentong Zhang)

cc_library(name = 'base',
           srcs = [
                   'kmp.cc',
                   'logging.cc',
                  ],
          )
